Design Entry;HDL Check||(null)||Checking HDL syntax of 'reg16.vhd'||(null);(null)||(null);(null)
Implementation;Place and Route;RootName:Complex_multiplier
Implementation;Place and Route||(null)||Please refer to the log file for details about 6 Info(s)||Complex_multiplier_layout_log.log;liberoaction://open_report/file/Complex_multiplier_layout_log.log||(null);(null)
HelpInfo,/home/rian/Microchip/Libero_SoC_2025.1/Libero_SoC/Synplify_Pro/lib/html,fpgahelp.qhc,synerrmsg.mp,/home/rian/Microchip/Libero_SoC_2025.1/Libero_SoC/Synplify_Pro/bin/assistant
