(part "TPS2051BDGN"
    (packageRef "SOP65P490X110-9N")
    (interface
        (port "1" (symbPinId 1) (portName "GND") (portType INOUT))
        (port "2" (symbPinId 2) (portName "IN_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "IN_2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "%EN†%") (portType INOUT))
        (port "5" (symbPinId 5) (portName "%OC%") (portType INOUT))
        (port "6" (symbPinId 6) (portName "OUT_1") (portType INOUT))
        (port "7" (symbPinId 7) (portName "OUT_2") (portType INOUT))
        (port "8" (symbPinId 8) (portName "OUT_3") (portType INOUT))
        (port "9" (symbPinId 9) (portName "EP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-TPS2051BDGN")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TPS2051BDGN?qs=ojKcPFmCWSUKr%252BVWzrslRQ%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TPS2051BDGN")
    (property "Description" "Single, Current-Limited, Power-Distribution Switch")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/TPS2051B")
    (property "symbolName1" "TPS2051BDGN")
)
