(part "PTN5150AHXMP"
    (packageRef "PTN5150AHXMP")
    (interface
        (port "1" (symbPinId 1) (portName "CC1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "CC2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "PORT") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VBUS_DET") (portType INOUT))
        (port "5" (symbPinId 5) (portName "ADR/CON_DET") (portType INOUT))
        (port "6" (symbPinId 6) (portName "INTB/OUT3") (portType INOUT))
        (port "7" (symbPinId 7) (portName "SDA/OUT1") (portType INOUT))
        (port "8" (symbPinId 8) (portName "SCL/OUT2") (portType INOUT))
        (port "9" (symbPinId 9) (portName "ID") (portType INOUT))
        (port "10" (symbPinId 10) (portName "GND") (portType INOUT))
        (port "11" (symbPinId 11) (portName "EXT_SEL") (portType INOUT))
        (port "12" (symbPinId 12) (portName "VDD") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "771-PTN5150AHXMP")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/NXP-Semiconductors/PTN5150AHXMP?qs=GIi83qBHgikdzCs4%252ByCwLg%3D%3D")
    (property "Manufacturer_Name" "NXP")
    (property "Manufacturer_Part_Number" "PTN5150AHXMP")
    (property "Description" "USB Controller USB Interface 12-X2QFN (1.6x1.6), 2.7V ~ 5.5V , 100 uA , -40C ~ 85C")
    (property "Datasheet_Link" "https://www.nxp.com/products/PTN5150?linkline=Data%20Sheet#documentation")
    (property "symbolName1" "PTN5150AHXMP")
)
