--------------------------------------------------------------------------------
-- Company: <Name>
--
-- File: Input_chain.vhd
--
-- Description:
--   Input chain for the MAX2771 GNSS front-end. The two-bit I/Q samples are
--   mixed with the sine and cosine generated by COREDDS_C0. Four instances of
--   Multiplier_simplified implement the complex carrier wipe-off:
--
--       I_out = I*cos + Q*sin
--       Q_out = Q*cos - I*sin
--
--   This is equivalent to (I + jQ)*(cos - j*sin). The result is registered and
--   output_valid marks every sample that can be accepted by the following block.
--
-- Important:
--   clk must be synchronous with the MAX2771 sample interface. If MAX_INPUT_CLK
--   belongs to another clock domain, place an asynchronous FIFO before this
--   block; a clock signal must not be used as a data-valid pulse.
--
-- Targeted device: <Family::PolarFireSoC> <Die::MPFS025T> <Package::FCSG325>
-- Author: <Name>
--------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity GNSS_Input_Chain is
    generic (
        -- COREDDS_C0 in the current Libero project has eight-bit outputs.
        DDS_WIDTH : positive := 5
    );
    port (
        -- Clock and reset. Reset is synchronous and active high for registers.
        clk     : in std_logic;
        DDS_clk : in std_logic;
        rst     : in std_logic;

        -- Raw two-bit I/Q samples from MAX2771.
        -- Encoding expected by Multiplier_simplified:
        --   bit 1 = sign, bit 0 = enable/high-amplitude indication.
        MAX_INPUT_I : in std_logic_vector(1 downto 0);
        MAX_INPUT_Q : in std_logic_vector(1 downto 0);
        sample_valid : in std_logic;

        -- Runtime frequency correction of the Libero DDS.
        DDS_FREQUENCY_OFFSET    : in std_logic_vector(4 downto 0);
        DDS_FREQUENCY_OFFSET_WE : in std_logic;
        DDS_INIT                : in std_logic;
        DDS_INIT_OVER           : out std_logic;

        -- Registered complex baseband sample for the following block.
        -- Each simplified product has DDS_WIDTH+1 bits. The addition/subtraction
        -- requires one more bit, hence DDS_WIDTH+2 bits at the output.
        OUTPUT_I    : out std_logic_vector(DDS_WIDTH+1 downto 0);
        OUTPUT_Q    : out std_logic_vector(DDS_WIDTH+1 downto 0);
        OUTPUT_VALID : out std_logic
    );
end GNSS_Input_Chain;

architecture architecture_Input_chain of GNSS_Input_Chain is
    -----------------------------------------------------------------------------
    -- Libero IP and project component declarations
    -----------------------------------------------------------------------------
    component DDS_PNFreq is
    -- Port list
    port(
        -- Inputs
        CLK            : in  std_logic;
        FREQ_OFFSET    : in  std_logic_vector(3 downto 0);
        NGRST          : in  std_logic;
        RSTN           : in  std_logic;
        PN_SIN         : in  std_logic;
        -- Outputs
        COSINE         : out std_logic_vector(4 downto 0);
        SINE           : out std_logic_vector(4 downto 0)
    );
    end component;

    component Multiplier_simplified is
        generic (
            data_width : integer := DDS_WIDTH
        );
        port (
            A : in  std_logic_vector(data_width-1 downto 0);
            B : in  std_logic_vector(1 downto 0);
            S : out std_logic_vector(data_width downto 0)
        );
    end component;

    -----------------------------------------------------------------------------
    -- DDS and complex-product signals
    -----------------------------------------------------------------------------
    type MAX_Signal is array (0 to 1) of std_logic_vector(1 downto 0);
    signal MAX_IQ : MAX_Signal; 

    type DDS_signal  is array (0 to 1) of std_logic_vector(DDS_WIDTH-1 downto 0);
    signal DDS_out : DDS_signal;

    type DDS_product is array (0 to 1) of std_logic_vector(DDS_WIDTH downto 0);
    signal I_DDS_prod : DDS_product;
    signal Q_DDS_prod : DDS_product;
    
    -----------------------------------------------------------------------------
    type MIXED_OUT is array (0 to 1) of signed(DDS_WIDTH+1 downto 0);
    signal mixed_output : MIXED_OUT;
    -- signal mixed_i_comb : signed(DDS_WIDTH+1 downto 0);
    -- signal mixed_q_comb : signed(DDS_WIDTH+1 downto 0);

begin
    assert DDS_WIDTH >= 2
        report "Input_chain requires DDS_WIDTH >= 2"
        severity failure;

    -----------------------------------------------------------------------------
    -- Local carrier generated by the existing Libero DDS IP Core
    -----------------------------------------------------------------------------
    U_CARRIER_DDS : DDS_PNFreq
        port map (
            CLK            => DDS_clk,
            FREQ_OFFSET    => DDS_FREQUENCY_OFFSET,
            NGRST          => not rst,
            RSTN           => not rst,
            COSINE         => DDS_out(0),
            INIT_OVER      => DDS_INIT_OVER,
            SINE           => DDS_out(1)
        );

    -----------------------------------------------------------------------------
    -- Four real products used to form one complex multiplication
    -----------------------------------------------------------------------------
    MAX_IQ(0) <= MAX_INPUT_I;
    MAX_IQ(1) <= MAX_INPUT_Q;

    ADPT_INPUT: 
    for i in 0 to 1 generate
        U_I_MULTIPLIER : Multiplier_simplified
            generic map (data_width => DDS_WIDTH)
            port map (
                A => DDS_out(i),
                B => MAX_IQ(0),
                S => I_DDS_prod(i)
            );

        U_Q_MULTIPLIER : Multiplier_simplified
            generic map (data_width => DDS_WIDTH)
            port map (
                A => DDS_out(i),
                B => MAX_IQ(1),
                S => Q_DDS_prod(i)
            );
    end generate;

    -- U_I_COS_MULTIPLIER : Multiplier_simplified
    --    generic map (data_width => DDS_WIDTH)
    --    port map (A => cosine_signal, B => MAX_INPUT_I, S => i_cos_product);

    -- U_I_SIN_MULTIPLIER : Multiplier_simplified
    --    generic map (data_width => DDS_WIDTH)
    --    port map (A => sine_signal, B => MAX_INPUT_I, S => i_sin_product);

    -- U_Q_COS_MULTIPLIER : Multiplier_simplified
    --    generic map (data_width => DDS_WIDTH)
    --    port map (A => cosine_signal, B => MAX_INPUT_Q, S => q_cos_product);

    -- U_Q_SIN_MULTIPLIER : Multiplier_simplified
    --    generic map (data_width => DDS_WIDTH)
    --    port map (A => sine_signal, B => MAX_INPUT_Q, S => q_sin_product);

    -----------------------------------------------------------------------------
    -- Complex carrier wipe-off
    --
    -- Products are explicitly sign-extended before the sum/subtraction. 
    -----------------------------------------------------------------------------
    mixed_output(0) <=  resize(signed(I_DDS_prod(0)), mixed_output(0)'length) -
                        resize(signed(Q_DDS_prod(1)), mixed_output(0)'length);

    mixed_output(1) <=  resize(signed(Q_DDS_prod(0)), mixed_output(1)'length) +
                        resize(signed(I_DDS_prod(1)), mixed_output(1)'length);

    -----------------------------------------------------------------------------
    -- Output register
    --
    -- OUTPUT_VALID is delayed by exactly one clock with respect to sample_valid.
    -- When sample_valid is low, the last output value is held.
    -----------------------------------------------------------------------------
    process (clk)
    begin
        if rising_edge(clk) then
            if rst = '1' then
                OUTPUT_I     <= (others => '0');
                OUTPUT_Q     <= (others => '0');
                OUTPUT_VALID <= '0';
            else
                OUTPUT_VALID <= sample_valid;

                if sample_valid = '1' then
                    OUTPUT_I <= std_logic_vector(mixed_output(0));
                    OUTPUT_Q <= std_logic_vector(mixed_output(1));
                end if;
            end if;
        end if;
    end process;
    
end architecture_Input_chain;
