(part "SI1416EDH-T1-GE3"
    (packageRef "SOT65P210X110-6N")
    (interface
        (port "1" (symbPinId 1) (portName "D_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "D_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "G") (portType INOUT))
        (port "4" (symbPinId 4) (portName "S") (portType INOUT))
        (port "5" (symbPinId 5) (portName "D_3") (portType INOUT))
        (port "6" (symbPinId 6) (portName "D_4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "78-SI1416EDH-T1-GE3")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Vishay-Semiconductors/SI1416EDH-T1-GE3?qs=pNKBmB2EQRiQP6xZUEPceg%3D%3D")
    (property "Manufacturer_Name" "Vishay")
    (property "Manufacturer_Part_Number" "SI1416EDH-T1-GE3")
    (property "Description" "Si1416EDH-T1-GE3 N-Channel MOSFET, 3.9 A, 30 V, 6-Pin SOT-363 Vishay")
    (property "Datasheet_Link" "http://www.vishay.com/docs/67580/si1416ed.pdf")
    (property "symbolName1" "SI1416EDH-T1-GE3")
)
